version: '3'
services:

  postgres:
    image: 'postgres:alpine'
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: estudos
      POSTGRES_PASSWORD: password
      POSTGRES_DB: estudos
      POSTGRES_HOST: postgres

volumes:
  postgres-volume: